services:
  rstudio:
    build: .
    # image: rocker/rstudio:4.4.3
    container_name: rstudio
    volumes:
      - .:/home/rstudio/AdventOfCode
      - ./rstudio-config:/home/.config
      - .cache:/home/rstudio/.cache
    environment:
      - DISABLE_AUTH=true
    ports:
      - '8787:8787'
    platform: linux/arm64